using System;
using System.Collections.Generic;
using System.Linq;
using C1.Web.Mvc;
using C1.Web.Mvc.Serialization;
using System.Web;
using System.Data;
using System.Web.Mvc;
using System.Data.Entity;
using CampusV4.Models;
using System.Web.Script.Serialization;

// This code was generated by C1 Scaffolder.

namespace CampusV4.Controllers.EarningsInput
{
    public partial class EarningsInputController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult EarningsInput(string mode)
        {
            EarningsInputViewModel model = new EarningsInputViewModel();
            if (mode == "1")
            {
                // 登録モード
                model.Mode = mode;
                model.Splitdelivery = 0;
                model.TaxExcluded = 0;
                model.ShipQuantity = 0;
                model.RorderRate = 0;
                model.EarningsForeigncurrency = 0;
                model.Tax = 0;
                model.Tax = 0;
                model.EarningsInternalcurrency = 0;
                model.ApprovalType = "1";
            }
            else if (mode == "2")
            {
                // 編集モード
                model.Mode = mode;
                GetEarningsInputData(ref model);
            }

            GetCombDataList(ref model);
            return View(model);
        }

        [HttpPost]
        public ActionResult EarningsInput(EarningsInputViewModel model)
        {
            GetCombDataList(ref model);
            return View(model);
        }

        [HttpPost]
        public ActionResult ProductionNumberList(EarningsInputViewModel model)
        {

            GetProductionNumberList(ref model);
            return View("ProductionNumberList", model);
            
            
        }


        [HttpPost]
        public ActionResult ScceptanceList(EarningsInputViewModel model)
        {
            GetScceptanceList(ref model);
            return View("ScceptanceList", model);


        }

        //分納選択画面
        [HttpPost]
        public JsonResult GetSplitdeliveryData()
        {
            JavaScriptSerializer sz = new JavaScriptSerializer();
            var dataList = new List<SplitDeliverySelectListData>();

            dataList.Add(new SplitDeliverySelectListData(1, 1, 10, 10, DateTime.Parse("2023/01/01").ToString("yyyy/MM/dd"), DateTime.Parse("2023 /01/10").ToString("yyyy/MM/dd"), DateTime.Parse("2023/02/01").ToString("yyyy/MM/dd"), true));
            dataList.Add(new SplitDeliverySelectListData(2, 2, 20, 40, DateTime.Parse("2023/01/02").ToString("yyyy/MM/dd"), DateTime.Parse("2023/01/20").ToString("yyyy/MM/dd"), DateTime.Parse("2023/02/02").ToString("yyyy/MM/dd"), false));
            dataList.Add(new SplitDeliverySelectListData(3, 3, 30, 90, DateTime.Parse("2023/01/03").ToString("yyyy/MM/dd"), DateTime.Parse("2023/01/30").ToString("yyyy/MM/dd"), DateTime.Now.ToString("yyyy/MM/dd"), true));

            string resultJson = "";

            resultJson = sz.Serialize(dataList);

            return Json(resultJson);
        }

        //リストボックス値取得
        private void GetCombDataList(ref EarningsInputViewModel model)
        {

            //税率
            var RateData = new List<MasterData>();
            RateData.Add(new MasterData("　", ""));
            RateData.Add(new MasterData("0", "0"));
            RateData.Add(new MasterData("8", "8"));
            RateData.Add(new MasterData("10", "10"));
            model.TaxRateList = RateData;


            // 担当者情報を取得
            var EmployeeData = new List<EmployeeData>();
            EmployeeData.Add(new EmployeeData("　", ""));
            EmployeeData.Add(new EmployeeData("USR00001", "佐藤　一郎"));
            EmployeeData.Add(new EmployeeData("USR00002", "佐藤　次郎"));
            EmployeeData.Add(new EmployeeData("USR00003", "佐藤　三郎"));
            EmployeeData.Add(new EmployeeData("USR00004", "佐藤　四朗"));
            EmployeeData.Add(new EmployeeData("USR00005", "佐藤　五郎"));
            model.EmployeeDataList = EmployeeData;
        }

        //売上データ取得
        private void GetEarningsInputData(ref EarningsInputViewModel model)
        {
            model.EarningsNo = "00001";
            model.OrderNum = "OR_00001";
            model.Splitdelivery = 2;
            model.CampusId = "0000010001";
            model.CompanyName = "京都金型工業";
            model.Subject = "件名";
            model.InvoiceNum = "IV_00001";
            model.InvoideDivision_ShipSlip = true;
            model.InvoideDivision_Invoice = false;
            model.SalesEmployeeCode = "USR00001";
            model.SalesEmployeeName = "佐藤 一郎";
            model.ShipEmployeeCode = "USR00002";
            model.ShipEmployeeName = "佐藤　次郎";
            model.ShipDate = DateTime.Parse("2023/02/01");
            model.AcceptanceEmployeeCode = "USR00003";
            model.AcceptanceEmployeeName = "佐藤　三郎";
            model.AcceptanceDate = DateTime.Parse("2023/02/02");
            model.TaxExcluded = 1000;
            model.ShipQuantity = 1000;
            model.unit = "式";
            model.AlignmentDate = DateTime.Parse("2023/02/03");
            model.RorderRate = 10;
            model.EarningsForeigncurrency = 10000;
            model.Tax = 100;
            model.TaxRate = "10";
            model.EarningsInternalcurrency = 1100;
            model.Notes ="備考";
            model.ApprovalFlg = false;
            model.ApprovalType = "1";

        }

        //製番詳細リスト取得
        private void GetProductionNumberList(ref EarningsInputViewModel model)
        {
            //var model = new OrderViewModel();
            var dataList = new List<ProductNumData>();
            dataList.Add(new ProductNumData("000003101", "A", "01", "10", "1,200", "12,000", "2023/01/10", "", ""));
            dataList.Add(new ProductNumData("000003101", "B", "01", "10", "1,200", "12,000", "2023/01/10", "", ""));

            model.ProductNumDataList = dataList;

            //List<ProductionNumberDetailListData_Earnings> ProductionNumberDataList = new List<ProductionNumberDetailListData_Earnings>();

            //ProductionNumberDataList.Add(new ProductionNumberDetailListData_Earnings("P001", 100,10,1000, DateTime.Parse("2023/01/01").ToString("yyyy/MM/dd"),"摘要1"));
            //ProductionNumberDataList.Add(new ProductionNumberDetailListData_Earnings("P001", 200, 20, 4000, DateTime.Parse("2023/02/01").ToString("yyyy/MM/dd"), "摘要2"));
            //ProductionNumberDataList.Add(new ProductionNumberDetailListData_Earnings("P001", 300, 30, 9000, DateTime.Parse("2023/03/01").ToString("yyyy/MM/dd"), "摘要3"));

            //model.GridProductionNumberDataList = ProductionNumberDataList;
        }

        //検収明細リスト取得
        private void GetScceptanceList(ref EarningsInputViewModel model)
        {
            //検収明細
            List<ScceptanceDetailListData_Earnings> ScceptanceDataList = new List<ScceptanceDetailListData_Earnings>();
            ScceptanceDataList.Add(new ScceptanceDetailListData_Earnings(1,"PO_0001",100,10,1000, DateTime.Parse("2023/01/01").ToString("yyyy/MM/dd"), DateTime.Parse("2023/01/02").ToString("yyyy/MM/dd"), DateTime.Parse("2023/01/03").ToString("yyyy/MM/dd")));
            ScceptanceDataList.Add(new ScceptanceDetailListData_Earnings(2, "PO_0002", 200, 20, 4000, DateTime.Parse("2023/02/01").ToString("yyyy/MM/dd"), DateTime.Parse("2023/02/02").ToString("yyyy/MM/dd"), DateTime.Parse("2023/02/03").ToString("yyyy/MM/dd")));
            ScceptanceDataList.Add(new ScceptanceDetailListData_Earnings(3, "PO_0003", 300, 30, 9000, DateTime.Parse("2023/03/01").ToString("yyyy/MM/dd"), DateTime.Parse("2023/03/02").ToString("yyyy/MM/dd"), DateTime.Parse("2023/03/03").ToString("yyyy/MM/dd")));

            model.GridScceptanceDataList = ScceptanceDataList;
        }
    }
}