using System;
using System.Collections.Generic;
using System.Web.Mvc;
using CampusV4.Models;
using Microsoft.Ajax.Utilities;

// This code was generated by C1 Scaffolder.

namespace CampusV4.Controllers.Inquiry
{
    public partial class InquiryListController : Controller
    {
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(InquiryListViewModel model)
        {
            {
                return View(model);
            }

        }

        public ActionResult Index()
        {
            {
                return View();
            }

        }
        
        public ActionResult InquiryList()
        {
            var model = new InquiryListViewModel();
         
            GetInitDataList(ref model);

            return View(model);
        }

        [HttpPost]
        public ActionResult InquiryList(InquiryListViewModel model)
        {

            GetInitDataList(ref model);
            GetListtDataList(ref model);

            return View(model);
        }

        //リストボックス値取得
        private void GetInitDataList(ref InquiryListViewModel model)
        {

            // 営業担当者情報を取得
            var TantoshaData = new List<EmployeeData>();
            TantoshaData.Add(new EmployeeData("　", ""));
            TantoshaData.Add(new EmployeeData("USR00001", "佐藤　一郎"));
            TantoshaData.Add(new EmployeeData("USR00002", "佐藤　次郎"));
            TantoshaData.Add(new EmployeeData("USR00003", "佐藤　三郎"));
            TantoshaData.Add(new EmployeeData("USR00004", "佐藤　四朗"));
            TantoshaData.Add(new EmployeeData("USR00005", "佐藤　五郎"));
            model.SalesEmployeeDataList = TantoshaData;

            // 進捗詳細Fromを取得
            var ProgressDetailsCodeListFrom = new List<MasterData>();
            ProgressDetailsCodeListFrom.Add(new MasterData("　", ""));
            ProgressDetailsCodeListFrom.Add(new MasterData("Prog1", "進捗詳細１"));
            ProgressDetailsCodeListFrom.Add(new MasterData("Prog2", "進捗詳細２"));
            ProgressDetailsCodeListFrom.Add(new MasterData("Prog3", "進捗詳細３"));
            ProgressDetailsCodeListFrom.Add(new MasterData("Prog4", "進捗詳細４"));
            ProgressDetailsCodeListFrom.Add(new MasterData("Prog5", "進捗詳細５"));
            model.ProgressDetailsCodeListFrom = ProgressDetailsCodeListFrom;

            // 進捗詳細Toを取得
            var ProgressDetailsCodeListTo = new List<MasterData>();
            ProgressDetailsCodeListTo.Add(new MasterData("　", ""));
            ProgressDetailsCodeListTo.Add(new MasterData("Prog1", "進捗詳細１"));
            ProgressDetailsCodeListTo.Add(new MasterData("Prog2", "進捗詳細２"));
            ProgressDetailsCodeListTo.Add(new MasterData("Prog3", "進捗詳細３"));
            ProgressDetailsCodeListTo.Add(new MasterData("Prog4", "進捗詳細４"));
            ProgressDetailsCodeListTo.Add(new MasterData("Prog5", "進捗詳細５"));
            model.ProgressDetailsCodeListTo = ProgressDetailsCodeListTo;

        }
        //引合一覧取得
        private void GetListtDataList(ref InquiryListViewModel model)
        {
            GetInitDataList(ref model);

            var dataList = new List<InquiryListData>();
            InquiryListData InquiryListData = new InquiryListData();
            //行番号
            InquiryListData.RowNumber = 1;
            //受注予定月
            InquiryListData.ExpectedOrderDate = DateTime.Now;
            //受付月
            InquiryListData.ReceptionDate = DateTime.Now;
            //内示マーク
            InquiryListData.InternalAnnouncementMark = "〇";
            //営業担当者
            InquiryListData.SalesEmploeeName = "佐藤　一郎";
            //得意先名
            InquiryListData.CustomerName = "得意先名１";
            //品名
            InquiryListData.ProductName = "金型A図枠組み";
            //引合番号
            InquiryListData.InquiryNumber = "3101";
            //受注確率
            InquiryListData.OrderProbability = 50;
            //外注原価
            InquiryListData.SubcontractCost = 1000;
            //加工比率
            InquiryListData.ProcessingRatio = 20;
            //見積金額
            InquiryListData.EstimatedAmount = 3000;
            //受注金額
            InquiryListData.OrderAmount = 4000;
            //最終受注金額
            InquiryListData.LastOrderAmount = 5000;
            //納期
            InquiryListData.ShippingDate = DateTime.Now;
            //更新日
            InquiryListData.UpdatedOn = DateTime.Now;
            //URL
            InquiryListData.URL = "/EstimateReplyInput/EstimateReplyInput?InquiryNumber=0001&CampusId=A001";

            dataList.Add(InquiryListData);

            InquiryListData InquiryListData1 = new InquiryListData();
            //行番号
            InquiryListData1.RowNumber = 2;
            //受注予定月
            InquiryListData1.ExpectedOrderDate = DateTime.Now;
            //受付月
            InquiryListData1.ReceptionDate = DateTime.Now;
            //内示マーク
            InquiryListData1.InternalAnnouncementMark = "〇";
            //営業担当者
            InquiryListData1.SalesEmploeeName = "佐藤　二郎";
            //得意先名
            InquiryListData1.CustomerName = "得意先名２";
            //品名
            InquiryListData1.ProductName = "金型B図枠組み";
            //引合番号
            InquiryListData1.InquiryNumber = "3102";
            //受注確率
            InquiryListData1.OrderProbability = 60;
            //外注原価
            InquiryListData1.SubcontractCost = 2000;
            //加工比率
            InquiryListData1.ProcessingRatio = 30;
            //見積金額
            InquiryListData1.EstimatedAmount = 4000;
            //受注金額
            InquiryListData1.OrderAmount = 5000;
            //最終受注金額
            InquiryListData1.LastOrderAmount = 6000;
            //納期
            InquiryListData1.ShippingDate = DateTime.Now;
            //更新日
            InquiryListData1.UpdatedOn = DateTime.Now;
            //URL
            InquiryListData1.URL = "/EstimateReplyInput/EstimateReplyInput?InquiryNumber=0001&CampusId=A001";

            dataList.Add(InquiryListData1);

            model.GridDataList = dataList;
        }
    }
}