using System;
using System.Collections.Generic;
using System.Linq;
using C1.Web.Mvc;
using C1.Web.Mvc.Serialization;
using System.Web;
using System.Data;
using System.Web.Mvc;
using System.Data.Entity;
using CampusV4.Models;

// This code was generated by C1 Scaffolder.

namespace CampusV4.Controllers.M_Employee
{
    public partial class M_EmployeeController : Controller
    {
        public ActionResult Index()
        {
            M_EmployeeSearchViewModel model = new M_EmployeeSearchViewModel();
            return View("EmployeeSearch",model);
        }

        //担当者マスタ一覧検索
        public ActionResult EmployeeSearch(M_EmployeeSearchViewModel model)
        {
            GetEmployeeListSearch(ref model);
            return View(model);
        }

        //担当者マスタ一覧削除
        public ActionResult EmployeeListDelete(M_EmployeeSearchViewModel model)
        {
            GetEmployeeListSearch(ref model);
            return View("EmployeeSearch", model);
        }
        //担当者マスタ詳細画面へ遷移
        public ActionResult EmployeeDetail(string UserId)
        {
            M_EmployeeViewModel model = new M_EmployeeViewModel();
            GetInitDataList(ref model);
            if (UserId == "")
            {
                model.Mode = "ins";
                model.IsRetired = "1";
            }
            else
            {
                model.Mode = "upd";
                GetEmployeeData(ref model);
            }

            return View(model);
        }

        //リストボックス値取得
        private void GetInitDataList(ref M_EmployeeViewModel model)
        {

            // 上長担当者情報を取得
            var TantoshaData = new List<EmployeeData>();
            TantoshaData.Add(new EmployeeData("　", ""));
            TantoshaData.Add(new EmployeeData("USR00001", "佐藤　一郎"));
            TantoshaData.Add(new EmployeeData("USR00002", "佐藤　次郎"));
            TantoshaData.Add(new EmployeeData("USR00003", "佐藤　三郎"));
            TantoshaData.Add(new EmployeeData("USR00004", "佐藤　四朗"));
            TantoshaData.Add(new EmployeeData("USR00005", "佐藤　五郎"));
            model.EmployeeList = TantoshaData;

            // 所属部門を取得
            var DepartmentList = new List<MasterData>();
            DepartmentList.Add(new MasterData("　", ""));
            DepartmentList.Add(new MasterData("001", "営業部"));
            DepartmentList.Add(new MasterData("002", "調達部"));
            model.DepartmentList = DepartmentList;

            // メニューを取得
            var MenuList = new List<MasterData>();
            MenuList.Add(new MasterData("　", ""));
            MenuList.Add(new MasterData("001", "メニュー１"));
            MenuList.Add(new MasterData("002", "メニュー２"));
            model.MenuList = MenuList;



        }

        private void GetEmployeeListSearch(ref M_EmployeeSearchViewModel model)
        {
            List<M_EmployeeViewModel> EmployeeDataList = new List<M_EmployeeViewModel>();
            M_EmployeeViewModel employeeData = new M_EmployeeViewModel();
            employeeData.UserId = "USR00001";
            employeeData.UserName = "佐藤　一郎";
            employeeData.UserNameAlt = "ICHIRO SATO";
            employeeData.DepartmentCode = "001";
            employeeData.DepartmentName = "営業部";
            employeeData.Email = "SATO1xxxx@xxx.com";
            employeeData.URL = "/M_Employee/EmployeeDetail?UserId="+ employeeData.UserId;
            EmployeeDataList.Add(employeeData);

            M_EmployeeViewModel employeeData1 = new M_EmployeeViewModel();
            employeeData1.UserId = "USR00002";
            employeeData1.UserName = "佐藤　二郎";
            employeeData1.UserNameAlt = "JIRO SATO";
            employeeData1.DepartmentCode = "001";
            employeeData1.DepartmentName = "営業部";
            employeeData1.Email = "SATO2xxxx@xxx.com";
            employeeData1.URL = "/M_Employee/EmployeeDetail?UserId=" + employeeData1.UserId;
            EmployeeDataList.Add(employeeData1);

            M_EmployeeViewModel employeeData2 = new M_EmployeeViewModel();
            employeeData2.UserId = "USR00003";
            employeeData2.UserName = "佐藤　三郎";
            employeeData2.UserNameAlt = "SABURO SATO";
            employeeData2.DepartmentCode = "002";
            employeeData2.DepartmentName = "調達部";
            employeeData2.Email = "SATO3xxxx@xxx.com";
            employeeData2.URL = "/M_Employee/EmployeeDetail?UserId=" + employeeData2.UserId;

            EmployeeDataList.Add(employeeData2);

            model.EmployeeDataList = EmployeeDataList;


        }

        private void GetEmployeeData(ref M_EmployeeViewModel model)
        {

            model.UserId = "USR00001";
            model.UserName = "佐藤　一郎";
            model.UserNameAlt = "ICHIRO SATO";
            model.DepartmentCode = "001";
            model.DepartmentName = "営業部";
            model.Email = "SATO1xxxx@xxx.com";

            model.Password = "abc123";
            model.MenuId = "001";
            model.MenuName = "メニュー１";
            model.PasswordChangeDate = DateTime.Parse("2023/01/30");
            model.IsRetired = "1";
            model.SupervisorPicCode = "USR00003";
            model.SupervisorPicName = "佐藤　三郎";
            model.IsApproverStr = "1";
            model.IsApprover = true;

            model.CreatedAt = DateTime.Parse("2023/01/01");
            model.CreatedBy = "USR00002";
            model.CreatedName = "佐藤　二郎";
            model.CreatedPid = "PID0001";
            model.UpdatedAt = DateTime.Parse("2023/01/30"); ;
            model.UpdatedBy = "USR00002";
            model.UpdatedName = "佐藤　二郎";
            model.UpdatedPid = "PID0001";
            model.DeletedAt = null;
            model.DeletedBy = "";
            model.DeletedName = "";
            model.DeletedPid = "";
    }
        }
}