using System;
using System.Collections.Generic;
using System.Linq;
using C1.Web.Mvc;
using C1.Web.Mvc.Serialization;
using System.Web;
using System.Data;
using System.Web.Mvc;
using System.Data.Entity;
using CampusV4.Models;
using Microsoft.Ajax.Utilities;

// This code was generated by C1 Scaffolder.

namespace CampusV4.Controllers.MeasurementCheckSheetInput
{
    public partial class MeasurementCheckSheetInputController : Controller
    {
        public ActionResult MeasurementCheckSheetInput()
        {
            MeasurementCheckSheetInputViewModel model = new MeasurementCheckSheetInputViewModel();
            GetCombDataList(ref model);
            return View(model);
        }

        [HttpPost]
        public ActionResult Search(MeasurementCheckSheetInputViewModel model)
        {
            GetCombDataList(ref model);
            GetMeasurementCheckSheetData(ref model);
            if(!model.ProductionEmployeeCode.IsNullOrWhiteSpace())
            {
                model.ProductionEmployeeName = model.EmployeeDataList.Find(m => m.EmployeeCode == model.ProductionEmployeeCode).EmployeeName;

            }
            return View("MeasurementCheckSheetInput", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Regist(MeasurementCheckSheetInputViewModel model)
        {
            return View("MeasurementCheckSheetInput", model);
        }

        private void GetMeasurementCheckSheetData(ref MeasurementCheckSheetInputViewModel model)
        {
            //受入番号
            model.PurchasingNumber = "0000000001";
            //製番
            model.ProductionNumber = "000012345A01";
            //分納回数
            model.Splitdelivery = 1;
            //CAMPUS-ID
            model.CampusId = "0000010001";
            //会社名
            model.CompanyName = "京都金型工業";
            //部署名
            model.DepartmentName = "営業部";
            //ご担当者様名
            model.SuppliersName = "佐藤　一郎";
            //連絡先
            model.PhoneNumber = "000-000-0000";
            //メールアドレス
            model.Email = "xxxxx@xxx.com";
            //部品番号
            model.PartsType = "B";
            //図面番号／型式
            model.DrawingNumber = "001602-A-B002";
            //部品名
            model.PartsName = "Upper Cull Block";
            //表面処理コード
            model.SurfaceTreatmentCode = "1001";
            //表面処理
            model.SurfaceTreatment = "表明処理１";
            //設計担当者コード
            model.DesignEmployeeCode = "USR00001";
            //設計担当者名
            model.DesignEmployeeName = "佐藤　一郎";
            //検査組立担当者コード
            model.TestAssemblyEmployeeCode = "USR00002";
            //検査組立担当者名
            model.TestAssemblyEmployeeName = "佐藤　次郎";
        }

        //リストボックス値取得
        private void GetCombDataList(ref MeasurementCheckSheetInputViewModel model)
        {
            // 担当者情報を取得
            var EmployeeData = new List<EmployeeData>();
            EmployeeData.Add(new EmployeeData("　", ""));
            EmployeeData.Add(new EmployeeData("USR00001", "佐藤　一郎"));
            EmployeeData.Add(new EmployeeData("USR00002", "佐藤　次郎"));
            EmployeeData.Add(new EmployeeData("USR00003", "佐藤　三郎"));
            EmployeeData.Add(new EmployeeData("USR00004", "佐藤　四朗"));
            EmployeeData.Add(new EmployeeData("USR00005", "佐藤　五郎"));
            model.EmployeeDataList = EmployeeData;

            //時間処理
            var TimeData = new List<MasterData>();
            TimeData.Add(new MasterData("　", ""));
            TimeData.Add(new MasterData("1", "9:00"));
            TimeData.Add(new MasterData("2", "10:00"));
            TimeData.Add(new MasterData("3", "11:00"));
            TimeData.Add(new MasterData("4", "12:00"));
            TimeData.Add(new MasterData("5", "13:00"));
            TimeData.Add(new MasterData("6", "14:00"));
            TimeData.Add(new MasterData("7", "15:00"));
            TimeData.Add(new MasterData("8", "16:00"));
            TimeData.Add(new MasterData("9", "17:00"));
            TimeData.Add(new MasterData("10", "18:00"));
            model.TimeList = TimeData;




        }
    }
}