using System;
using System.Collections.Generic;
using System.Linq;
using C1.Web.Mvc;
using C1.Web.Mvc.Serialization;
using System.Web;
using System.Data;
using System.Web.Mvc;
using System.Data.Entity;
using CampusV4.Models;

// This code was generated by C1 Scaffolder.

namespace CampusV4.Controllers.Portal
{
    public partial class PortalController : Controller
    {
        public ActionResult Index(string loginID)
        {
            if (loginID == "")
            {
                PortalInternalViewModel model = new PortalInternalViewModel();
                GetPortalData(ref model);
                return View("PortalInternal", model);

            }
            else
            {
                PortalExternalViewModel model = new PortalExternalViewModel();
                GetPortalExternalData(ref model);
                return View("PortalExternal", model);
            }
        }

        public ActionResult PortalExternalDetail(string Id)
        {
            PortalExternalDetailViewModel model = new PortalExternalDetailViewModel();
            GetPortalExternalDetailData(ref model);
            return View(model);
        }

        // ダッシュボードセルクリック
        [HttpPost]
        public ActionResult PortalInternalDetail(PortalInternalViewModel portalInternalmodel)
        {
            if (!Request.IsAjaxRequest())
            {
                return new EmptyResult();
            }

            PortalInternalDetailViewModel model = new PortalInternalDetailViewModel();
            GetPortalDetailData(ref model, portalInternalmodel.SelectCol);

            // 部分ビューを返す
            return PartialView("PortalInternalDetail", model);
        }

        //明細Gridクリック
        [HttpPost]
        public ActionResult PortalInternalDetailDetail(PortalInternalDetailViewModel portalInternalDetailmodel)
        {
            if (!Request.IsAjaxRequest())
            {
                return new EmptyResult();
            }

            PortalInternalDetailDetailViewModel model = new PortalInternalDetailDetailViewModel();
            GetPortalDetailDetailData(ref model, portalInternalDetailmodel.SelectProductionNumber);

            // 部分ビューを返す
            return PartialView("PortalInternalDetailDetail", model);
        }

        //ダッシュボード値取得
        private void GetPortalData(ref PortalInternalViewModel model)
        {
            List<PortalInternalDashboardViewModel> portalInternalDashboardList = new List<PortalInternalDashboardViewModel>();
            PortalInternalDashboardViewModel portalInternalDashboardViewModel = new PortalInternalDashboardViewModel();
            portalInternalDashboardViewModel.EstimatedShippingNum = 1000;
            portalInternalDashboardViewModel.EstimatedDesignNum = 2000;
            portalInternalDashboardViewModel.EstimatedOrderNum = 3000;
            portalInternalDashboardViewModel.EstimatedComeInNum = 4000;
            portalInternalDashboardViewModel.PurchaseAmount = 5000;
            portalInternalDashboardViewModel.EarningsAmount = 6000;

            portalInternalDashboardList.Add(portalInternalDashboardViewModel);

            model.PortalInternalDashboardList = portalInternalDashboardList;
        }

        //明細部の値取得
        private void GetPortalDetailData(ref PortalInternalDetailViewModel model,string selectCol)
        {
            List<PortalInternalDetailData> PortalInternalDataList = new List<PortalInternalDetailData>();
            PortalInternalDetailData portalInternalData = new PortalInternalDetailData();
            portalInternalData.RowNum = 1;
            portalInternalData.CustomerName = "得意先名1";
            portalInternalData.Subject = "件名1";
            portalInternalData.ProductionNumber = selectCol + "0001-001";
            portalInternalData.Quantity = 10;
            portalInternalData.Unit = "式";
            portalInternalData.UnitPrice = 100;
            portalInternalData.Aamount =1000;
            PortalInternalDataList.Add(portalInternalData);

            PortalInternalDetailData portalInternalData1 = new PortalInternalDetailData();
            portalInternalData1.RowNum = 2;
            portalInternalData1.CustomerName = "得意先名2";
            portalInternalData1.Subject = "件名2";
            portalInternalData1.ProductionNumber = selectCol + "0002-001";
            portalInternalData1.Quantity = 20;
            portalInternalData1.Unit = "式";
            portalInternalData1.UnitPrice = 200;
            portalInternalData1.Aamount = 4000;
            PortalInternalDataList.Add(portalInternalData1);

            PortalInternalDetailData portalInternalData2 = new PortalInternalDetailData();
            portalInternalData2.RowNum = 3;
            portalInternalData2.CustomerName =  "得意先名3";
            portalInternalData2.Subject = "件名3";
            portalInternalData2.ProductionNumber = selectCol + "0003-001";
            portalInternalData2.Quantity = 30;
            portalInternalData2.Unit = "式";
            portalInternalData2.UnitPrice = 300;
            portalInternalData2.Aamount = 9000; PortalInternalDataList.Add(portalInternalData2);

            PortalInternalDetailData portalInternalData3 = new PortalInternalDetailData();
            portalInternalData3.RowNum = 4;
            portalInternalData3.CustomerName = "得意先名4";
            portalInternalData3.Subject = "件名4";
            portalInternalData3.ProductionNumber = selectCol + "0004-001";
            portalInternalData3.Quantity = 40;
            portalInternalData3.Unit = "式";
            portalInternalData3.UnitPrice = 300;
            portalInternalData3.Aamount = 12000; 
            PortalInternalDataList.Add(portalInternalData3);

            model.PortalInternalDetailDataList = PortalInternalDataList;
        }

        //明細の明細部の値取得
        private void GetPortalDetailDetailData(ref PortalInternalDetailDetailViewModel model, string SelectProductionNumber)
        {
            List<PortalInternalDetailDetailData> PortalInternalDetailDetailDataList = new List<PortalInternalDetailDetailData>();
            PortalInternalDetailDetailData portalInternalData = new PortalInternalDetailDetailData();
            portalInternalData.RowNum = 1;
            portalInternalData.ProductionNumber = SelectProductionNumber;
            portalInternalData.PartsName = "部品名1";
            portalInternalData.PartnerFactoryName = "パートナー工場1";
            portalInternalData.DrawingNum = "図面番号／型式1";
            portalInternalData.Quantity = 10;
            portalInternalData.UnitPrice = 100;
            portalInternalData.Aamount = 1000;
            PortalInternalDetailDetailDataList.Add(portalInternalData);

            PortalInternalDetailDetailData portalInternalData1 = new PortalInternalDetailDetailData();
            portalInternalData1.RowNum = 2;
            portalInternalData1.ProductionNumber = SelectProductionNumber;
            portalInternalData1.PartsName = "部品名2";
            portalInternalData1.PartnerFactoryName = "パートナー工場2";
            portalInternalData1.DrawingNum = "図面番号／型式2";
            portalInternalData1.Quantity = 20;
            portalInternalData1.UnitPrice = 200;
            portalInternalData1.Aamount = 4000;
            PortalInternalDetailDetailDataList.Add(portalInternalData1);

            PortalInternalDetailDetailData portalInternalData2 = new PortalInternalDetailDetailData();
            portalInternalData2.RowNum = 3;
            portalInternalData2.ProductionNumber = SelectProductionNumber;
            portalInternalData2.PartsName = "部品名3";
            portalInternalData2.PartnerFactoryName = "パートナー工場3";
            portalInternalData2.DrawingNum = "図面番号／型式3";
            portalInternalData2.Quantity = 30;
            portalInternalData2.UnitPrice = 300;
            portalInternalData2.Aamount = 9000;
            PortalInternalDetailDetailDataList.Add(portalInternalData2);

            PortalInternalDetailDetailData portalInternalData3 = new PortalInternalDetailDetailData();
            portalInternalData3.RowNum = 4;
            portalInternalData3.ProductionNumber = SelectProductionNumber;
            portalInternalData3.PartsName = "部品名4";
            portalInternalData3.PartnerFactoryName = "パートナー工場4";
            portalInternalData3.DrawingNum = "図面番号／型式4";
            portalInternalData3.Quantity = 40;
            portalInternalData3.UnitPrice = 300;
            portalInternalData3.Aamount = 12000;
            PortalInternalDetailDetailDataList.Add(portalInternalData3);

            model.PortalInternalDetailDetailDataList = PortalInternalDetailDetailDataList;
        }

        //社外ポータルの値取得
        private void GetPortalExternalData(ref PortalExternalViewModel model)
        {
            List<PortalExternalPartnerData> portalExternalPartnerDataList = new List<PortalExternalPartnerData>();
            PortalExternalPartnerData portalExternalPartnerData = new PortalExternalPartnerData();
            portalExternalPartnerData.Id = "0001";
            portalExternalPartnerData.FilePath = "/Content/SampleImages/Sample1.jpg";
            portalExternalPartnerData.FileName = "SampleImage1";
            portalExternalPartnerDataList.Add(portalExternalPartnerData);

            PortalExternalPartnerData portalExternalPartnerData1 = new PortalExternalPartnerData();
            portalExternalPartnerData1.Id = "0002";
            portalExternalPartnerData1.FilePath = "/Content/SampleImages/Sample2.jpg";
            portalExternalPartnerData1.FileName = "SampleImage2";
            portalExternalPartnerDataList.Add(portalExternalPartnerData1);

            List<PortalExternalPartnerData> portalExternalPartnerAchievementDataList = new List<PortalExternalPartnerData>();
            PortalExternalPartnerData portalExternalPartnerAchievementData = new PortalExternalPartnerData();
            portalExternalPartnerAchievementData.Id = "0003";
            portalExternalPartnerAchievementData.FilePath = "/Content/SampleImages/Sample3.png";
            portalExternalPartnerAchievementData.FileName = "SampleImage3";
            portalExternalPartnerAchievementDataList.Add(portalExternalPartnerAchievementData);

            PortalExternalPartnerData portalExternalPartnerAchievementData1 = new PortalExternalPartnerData();
            portalExternalPartnerAchievementData1.Id = "0004";
            portalExternalPartnerAchievementData1.FilePath = "/Content/SampleImages/Sample4.jpg";
            portalExternalPartnerAchievementData1.FileName = "SampleImage4";
            portalExternalPartnerAchievementDataList.Add(portalExternalPartnerAchievementData1);

            PortalExternalPartnerData portalExternalPartnerAchievementData2 = new PortalExternalPartnerData();
            portalExternalPartnerAchievementData2.Id = "0005";
            portalExternalPartnerAchievementData2.FilePath = "/Content/SampleImages/Sample5.jpg";
            portalExternalPartnerAchievementData2.FileName = "SampleImage5";
            portalExternalPartnerAchievementDataList.Add(portalExternalPartnerAchievementData2);


            model.PortalExternalPartnerDataList = portalExternalPartnerDataList;
            model.PortalExternalPartnerAchievementDataList = portalExternalPartnerAchievementDataList;
        }

        //社外ポータルの詳細取得
        private void GetPortalExternalDetailData(ref PortalExternalDetailViewModel model)
        {
            //品種
            model.Variety = "ZX-A001";
            //製作区分
            model.ProductionCategory = "A";
            //フレームセット数
            model.FreamSetNum = 1000;
            //材質
            model.Material = "材質A";
            //表面処理
            model.SurfaceTreatment = "表面処理A";
            //PKG数　連　From
            model.PkgNumSerialFrom = 1000;
            //PKG数　連　To
            model.PkgNumSerialTo = 1500;
            //PKG数　列　From
            model.PkgNumColumnFrom = 2000;
            //PKG数　列　To
            model.PkgNumColumnTo = 2500;
            //PKGサイズ　幅　From
            model.PkgSizeWidthFrom = 3000;
            //PKGサイズ　幅　To
            model.PkgSizeWidthTo = 3500;
            //PKGサイズ　長　From
            model.PkgSizeLengthFrom = 4000;
            //PKGサイズ　長　To
            model.PkgSizeLengthTo = 4500;
            //PKGサイズ　厚　From
            model.PkgSizeThicknessFrom = 5000;
            //PKGサイズ　厚　To
            model.PkgSizeThicknessTo = 5500;
            //リードフレーム　幅　From
            model.LeadFrameWidthFrom = 6000;
            //リードフレーム　幅　To
            model.LeadFrameWidthTo = 6500;
            //リードフレーム　長　From
            model.LeadFrameLengthFrom = 7000;
            //リードフレーム　長　To
            model.LeadFrameLengthTo = 7500;
            //リードフレーム　厚　From
            model.LeadFrameThicknessFrom = 8000;
            //リードフレーム　厚　To
            model.LeadFrameThicknessTo = 8500;

        }

    }

}