using System;
using System.Collections.Generic;
using System.Linq;
using C1.Web.Mvc;
using C1.Web.Mvc.Serialization;
using System.Web;
using System.Data;
using System.Web.Mvc;
using System.Data.Entity;
using CampusV4.Models;
using System.Web.Script.Serialization;

// This code was generated by C1 Scaffolder.

namespace CampusV4.Controllers.ProductionControlAlignmentDataOutput
{
    public partial class ProductionControlAlignmentDataOutputController : Controller
    {
        
        public ActionResult ProductionControlAlignmentDataOutput()
        {
            ProductionControlAlignmentDataViewModel model = new ProductionControlAlignmentDataViewModel();
            model.ProcessKbn = "1";
            model.SlipKbnOrderJ = true;
            model.SlipKbnOrderH = true;
            model.Pattern = "1";
            GetComboDataList(ref model);
            return View(model);
        }

        //リストボックス値取得
        private void GetComboDataList(ref ProductionControlAlignmentDataViewModel model)
        {

            // 担当者情報を取得
            var EmployeeDataList = new List<EmployeeData>();
            EmployeeDataList.Add(new EmployeeData("　", ""));
            EmployeeDataList.Add(new EmployeeData("USR00001", "佐藤　一郎"));
            EmployeeDataList.Add(new EmployeeData("USR00002", "佐藤　次郎"));
            EmployeeDataList.Add(new EmployeeData("USR00003", "佐藤　三郎"));
            EmployeeDataList.Add(new EmployeeData("USR00004", "佐藤　四朗"));
            EmployeeDataList.Add(new EmployeeData("USR00005", "佐藤　五郎"));
            model.EmployeeDataList = EmployeeDataList;


        }
        [HttpPost]
        public JsonResult GetProductionControlAlignmentDataOutputDelete()
        {
            JavaScriptSerializer sz = new JavaScriptSerializer();
            var dataList = new List<ProductionControlAlignmentDataDeleteData>();
            dataList.Add(new ProductionControlAlignmentDataDeleteData(1, "2023/01/01", "2023/01/01～2023/01/31", "0000001"));
            dataList.Add(new ProductionControlAlignmentDataDeleteData(2, "2023/02/01", "2023/02/01～2023/02/28", "0000002"));
            dataList.Add(new ProductionControlAlignmentDataDeleteData(3, "2023/03/01", "2023/03/01～2023/03/31", "0000003"));
            dataList.Add(new ProductionControlAlignmentDataDeleteData(4, "2023/04/01", "2023/04/01～2023/04/30", "0000004"));
            dataList.Add(new ProductionControlAlignmentDataDeleteData(5, "2023/05/01", "2023/05/01～2023/05/31", "0000005"));
            dataList.Add(new ProductionControlAlignmentDataDeleteData(6, "2023/06/01", "2023/06/01～2023/06/30", "0000006"));

            string str = sz.Serialize(dataList);
            return Json(str);
        }

    }
}