using System;
using System.Collections.Generic;
using System.Linq;
using C1.Web.Mvc;
using C1.Web.Mvc.Serialization;
using System.Web;
using System.Data;
using System.Web.Mvc;
using System.Data.Entity;
using CampusV4.Models;
using System.Web.UI.WebControls;

// This code was generated by C1 Scaffolder.

namespace CampusV4.Controllers.ProgressList
{
    public partial class ProgressListController : Controller
    {

        public ActionResult ProgressList()
        {
            ProgressListViewModel model = new ProgressListViewModel();
            GetComboDataList(ref model);
            return View(model);
        }

        [HttpPost]
        public ActionResult ProgressList(ProgressListViewModel model)
        {
            GetComboDataList(ref model);
            GetProgresListData(ref model);
            return View(model);
        }

        //リストボックス値取得
        private void GetComboDataList(ref ProgressListViewModel model)
        {

            // 営業担当者情報を取得
            var TantoshaData = new List<EmployeeData>();
            TantoshaData.Add(new EmployeeData("　", ""));
            TantoshaData.Add(new EmployeeData("USR00001", "佐藤　一郎"));
            TantoshaData.Add(new EmployeeData("USR00002", "佐藤　次郎"));
            TantoshaData.Add(new EmployeeData("USR00003", "佐藤　三郎"));
            TantoshaData.Add(new EmployeeData("USR00004", "佐藤　四朗"));
            TantoshaData.Add(new EmployeeData("USR00005", "佐藤　五郎"));
            model.SalesEmployeeDataList = TantoshaData;

            // ステータスを取得
            var StatusDataList = new List<MasterData>();
            StatusDataList.Add(new MasterData("　", ""));
            StatusDataList.Add(new MasterData("A", "ステータスA"));
            StatusDataList.Add(new MasterData("B", "ステータスB"));
            StatusDataList.Add(new MasterData("C", "ステータスC"));
            StatusDataList.Add(new MasterData("D", "ステータスD"));
            StatusDataList.Add(new MasterData("E", "ステータスE"));
            model.StatusDataList = StatusDataList;


        }

        //一覧取得
        private void GetProgresListData(ref ProgressListViewModel model)
        {
            var dataList = new List<ProgressListData>();
            ProgressListData progressListData = new ProgressListData();
            //見積マーク
            progressListData.EstimatedMark = "引";
            //引合番号
            progressListData.InquiryNumber = "0001";
            //進捗詳細
            progressListData.ProgressDetails = "";
            //内示マーク
            progressListData.InternalAnnouncementMark = "内";
            //依頼日
            progressListData.RequestDate = DateTime.Parse("2023/01/01");
            //得意先名
            progressListData.CustomerName = "得意先名１";
            //品名
            progressListData.ProductName = "金型A図枠組み";
            //原価資料作成予定日
            progressListData.ExpectedCostDocumentDate = DateTime.Parse("2023/01/02");
            //原価見積作成予定日
            progressListData.ExpectedCostEstimateDate = DateTime.Parse("2023/01/03");
            //出荷予定日
            progressListData.EstimatedShippingDate = DateTime.Parse("2023/01/10");
            //発注日
            progressListData.OrderDate = DateTime.Parse("2023/01/11");
            //入荷予定日
            progressListData.ExpectedReceiptDate = DateTime.Parse("2023/01/12");
            //完成予定日
            progressListData.ExpectedCompleteDate = DateTime.Parse("2023/01/13");
            //出荷指示日
            progressListData.ShippingInstructionDate = DateTime.Parse("2023/01/14");
            //出荷日
            progressListData.ShipDate = DateTime.Parse("2023/01/15");
            //営業担当者
            progressListData.SalesEmployeeName = "佐藤　一郎";
            dataList.Add(progressListData);


            ProgressListData progressListData1 = new ProgressListData();
            //見積マーク
            progressListData1.EstimatedMark = "依";
            //引合番号
            progressListData1.InquiryNumber = "0002";
            //進捗詳細
            progressListData1.ProgressDetails = "";
            //内示マーク
            progressListData1.InternalAnnouncementMark = "";
            //依頼日
            progressListData1.RequestDate = DateTime.Parse("2023/02/01");
            //得意先名
            progressListData1.CustomerName = "得意先名２";
            //品名
            progressListData1.ProductName = "金型B図枠組み";
            //原価資料作成予定日
            progressListData1.ExpectedCostDocumentDate = DateTime.Parse("2023/02/02");
            //原価見積作成予定日
            progressListData1.ExpectedCostEstimateDate = DateTime.Parse("2023/02/03");
            //出荷予定日
            progressListData1.EstimatedShippingDate = DateTime.Parse("2023/02/10");
            //発注日
            progressListData1.OrderDate = DateTime.Parse("2023/02/11");
            //入荷予定日
            progressListData1.ExpectedReceiptDate = DateTime.Parse("2023/02/12");
            //完成予定日
            progressListData1.ExpectedCompleteDate = DateTime.Parse("2023/02/13");
            //出荷指示日
            progressListData1.ShippingInstructionDate = DateTime.Parse("2023/02/14");
            //出荷日
            progressListData1.ShipDate = DateTime.Parse("2023/02/15");
            //営業担当者
            progressListData1.SalesEmployeeName = "佐藤　二郎";

            dataList.Add(progressListData1);
            model.GridDataList = dataList;
        }

    }


}